"""Builds the fonts embedded in intake/waiver PDFs (F27) -> src/pdf/fonts.generated.ts.

Sources: the @fontsource-variable packages already installed for the web app (Noto Sans Thai, Noto Naskh Arabic,
DM Sans; all SIL Open Font License 1.1, see src/pdf/FONTS-OFL.txt). Each variable font is pinned to a static
Regular (400) and Bold (700) instance and subset to the script's Unicode blocks, keeping the OpenType layout
tables (GSUB/GPOS) so fontkit can shape Arabic joining forms and Thai marks.

Run only when the fonts change (needs Python 3 + fonttools + brotli):
  python3 -m venv /tmp/ft && /tmp/ft/bin/pip install fonttools brotli
  /tmp/ft/bin/python packages/services/scripts/pdf-fonts.py
"""

import base64
import glob
import io
import os
import sys

from fontTools import subset
from fontTools.merge import Merger
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
OUT = os.path.join(ROOT, 'packages', 'services', 'src', 'pdf', 'fonts.generated.ts')


def source(pkg: str, file: str) -> str:
    hits = glob.glob(os.path.join(ROOT, 'node_modules', '.pnpm', f'@fontsource-variable+{pkg}@*', 'node_modules',
                                  '@fontsource-variable', pkg, 'files', file))
    if not hits:
        sys.exit(f'missing {pkg}/{file}: run pnpm install first')
    return sorted(hits)[-1]


def static(path: str, weight: int) -> TTFont:
    font = TTFont(path)
    axes = {a.axisTag: a for a in font['fvar'].axes}
    lo, hi = axes['wght'].minValue, axes['wght'].maxValue
    return instancer.instantiateVariableFont(font, {'wght': max(lo, min(hi, weight))}, updateFontNames=False)


def to_bytes(font: TTFont) -> bytes:
    buf = io.BytesIO()
    font.flavor = None
    font.save(buf)
    return buf.getvalue()


def subset_font(font: TTFont, unicodes: list[int]) -> bytes:
    opts = subset.Options()
    opts.layout_features = ['*']
    opts.name_IDs = ['*']
    opts.notdef_outline = True
    opts.hinting = False
    opts.desubroutinize = True
    s = subset.Subsetter(opts)
    s.populate(unicodes=unicodes)
    s.subset(font)
    return to_bytes(font)


def rng(a: int, b: int) -> list[int]:
    return list(range(a, b + 1))


COMMON = [0x20, 0xA0, 0x200C, 0x200D, 0x200E, 0x200F, 0x25CC]
THAI = COMMON + rng(0x0E00, 0x0E7F)
ARABIC = COMMON + rng(0x0600, 0x06FF) + rng(0xFB50, 0xFDFF) + rng(0xFE70, 0xFEFF)
LATIN = rng(0x20, 0x7E) + rng(0xA0, 0x24F) + rng(0x2000, 0x206F) + [0x20AC, 0x2122, 0x2116, 0x2190, 0x2192, 0x2713]


def latin(weight: int) -> bytes:
    # DM Sans ships Latin and Latin Extended as two files: merge the static instances, then subset.
    parts = []
    for name in ('dm-sans-latin-wght-normal.woff2', 'dm-sans-latin-ext-wght-normal.woff2'):
        p = os.path.join('/tmp', f'pdf-font-{weight}-{name}.ttf')
        with open(p, 'wb') as fh:
            fh.write(to_bytes(static(source('dm-sans', name), weight)))
        parts.append(p)
    merged = Merger().merge(parts)
    for p in parts:
        os.remove(p)
    return subset_font(merged, LATIN)


FONTS = {
    'latin': lambda w: latin(w),
    'thai': lambda w: subset_font(static(source('noto-sans-thai', 'noto-sans-thai-thai-wght-normal.woff2'), w), THAI),
    'arabic': lambda w: subset_font(
        static(source('noto-naskh-arabic', 'noto-naskh-arabic-arabic-wght-normal.woff2'), w), ARABIC),
}

def ranges(data: bytes) -> str:
    cps = sorted(TTFont(io.BytesIO(data)).getBestCmap().keys())
    out, start, prev = [], cps[0], cps[0]
    for cp in cps[1:] + [None]:
        if cp is not None and cp == prev + 1:
            prev = cp
            continue
        out.append(f'[{start}, {prev}]')
        if cp is not None:
            start = prev = cp
    return ', '.join(out)


lines = [
    '// Generated by packages/services/scripts/pdf-fonts.py, do not edit. Fonts: SIL OFL 1.1 (FONTS-OFL.txt):',
    '// DM Sans (latin), Noto Sans Thai (thai), Noto Naskh Arabic (arabic); static 400/700 instances, subset.',
    'export const PDF_FONTS = {',
]
coverage = []
for key, build in FONTS.items():
    for weight, suffix in ((400, 'Regular'), (700, 'Bold')):
        data = build(weight)
        print(f'{key}{suffix}: {len(data) // 1024} KB', file=sys.stderr)
        lines.append(f"  {key}{suffix}: '{base64.b64encode(data).decode()}',")
        if weight == 400:
            coverage.append(f'  {key}: [{ranges(data)}],')
lines += ['} as const', 'export type PdfFontKey = keyof typeof PDF_FONTS', '',
          '/** Code point ranges each family covers (same for both weights). */',
          'export const PDF_FONT_COVERAGE: Record<\'latin\' | \'thai\' | \'arabic\', [number, number][]> = {',
          *coverage, '}', '']
with open(OUT, 'w') as fh:
    fh.write('\n'.join(lines))
print(f'wrote {os.path.relpath(OUT, ROOT)}', file=sys.stderr)
